### ISSUE TITLE
Implement new search schema

### ISSUE THREAD

**Issue by alipski** [CanDIG/candig-schemas#7]
Implement and compile .proto files for the new search schema.

sample query structure:

"query":{
   "logic":{
      "AND":[
         "A",
         "B"
      ]
   }   "components":[
      {
         "component_id":"A",
         "table":"diagnosis",
         "filter":[
            {
               "field":"datasetId",               
               "value":"WyJjb25jb3JkYW5jZV9Nb250cmVhbCJd",               
               "operator":"="
            },
            {
               "field":"cancerType",              
               "value":"carcinoma" ,              
               "operator":"in"
            }
         ]
      },
      {
         "component_id":"B",
         "table":"variant",
         "filter":[
            {
               "field":"datasetId",
               "value":"WyJjb25jb3JkYW5jZV9Nb250cmVhbCJd",
               "operator":"="
            },
            {
               "field":"referenceName",
               "value":"chr13",
               "operator":"=",

            },
            {
               "field":"start",
               "value":32936732,
               "operator":"="
            },
            {
               "field":"end",
               "value":32936733,
               "operator":"="
            }
         ]
      }
   ],
   "return":[
      {
         "table":"treatment",
         "field":[
            "startDate",
            "stopDate",
            "drugList"
         ]
      },
      {
         "table":"sample",
         "field":[
            "tumourContent"
         ]
      }
   ],
   "limit":1000
}

**Comment by HaoyuanLi** [comment]
`"query":{
"logic":{
"AND":[
"A",
"B"
]
} "components":[
{
"component_id":"A",
"table":"diagnosis",
"filter":[
{
"field":"datasetId",
"value":"WyJjb25jb3JkYW5jZV9Nb250cmVhbCJd",
"operator":"="
},
{
"field":"cancerType",
"value":"carcinoma" ,
"operator":"in"
}
]
},
{
"component_id":"B",
"table":"variant",
"filter":[
{
"field":"datasetId",
"value":"WyJjb25jb3JkYW5jZV9Nb250cmVhbCJd",
"operator":"="
},
{
"field":"referenceName",
"value":"chr13",
"operator":"=",

        },
        {
           "field":"start",
           "value":32936732,
           "operator":"="
        },
        {
           "field":"end",
           "value":32936733,
           "operator":"="
        }
     ]
  }
],
"return":[
{
"table":"treatment",
"field":[
"startDate",
"stopDate",
"drugList"
]
},
{
"table":"sample",
"field":[
"tumourContent"
]
}
],
"limit":1000
}`

**Comment by ljdursi** [comment]
Don't implement this, or other new functionality, in the Flask server.

This particular functionality is an especially poor match - it doesn't scale.  You'll have to change the proto files and implementation every time a new type of search is made available, or every time one of the component services changes its response format.  We need to find a scalable way to compose queries across APIs, and it doesn't make sense to implement that inside of one of the API services.

And just generally, we determined that the Flask server was functionality-complete for v1.0.  Adding more and more functionality into the Flask server is why it is hard to get deployed at all, and why the security staff have troubles deciding how to safely deploy it; the "everything in one process" approach makes it hard to figure out where it can safely go.  The API gateway helped a little bit, but having one process that has access to all the data and makes its own decisions about whether or not it's allowed to access some data is a data breach waiting to happen.

Besides but not unrelated to the security problems, having all the functionality in one place inevitably leads to code maintainability problems.  Check out, for instance,  https://codeclimate.com/github/CanDIG/ga4gh-server/code?sort=maintainability .  The code base is large, repetitive, hard to work with, and slow to test.  

All of the above might be worth it if there was a huge advantage to having one process handle the metadata, the variants, the RNA expression, etc, but there isn't; they are very different types of data, and combining them under one umbrella doesn't gain us anything.

The work Adam and Jimmy have been doing has helped clean up the code a great deal and get it ready for production, but in the end there's a reason UCSC abandoned this code.  It's gotten us to where we are, which is great, but it's not going to get us where we're going.   Any new functionality added to the Flask server is just that much more code which is going to be maintenance-only in a few months, and read-only in 2019.

**Comment by alipski** [comment]
Those are all valid points and any amount of work changing the "everything in one process" approach we have right now would involve a complete overhaul of the ga4gh design. It's my understanding though that if we want to implement something like the Discovery Search API, on some level we have to change our protobuf search schemas? Is any cross-API search we implement from this point on going to be a wrapper around existing searches then?

**Comment by ljdursi** [comment]
Completely true; but there's a difference between doing the refactoring of the functionality of the server now, which is admittedly a big project and can be usefully deferred, and adding still more functionality to the server, which adds to the eventual problem without gaining much for us.

There needs to be a way of searching the diagnosis table for diagnoses + treatment table for treatments, which I understand largely exists now, and a way of searching the variants by annotation (e.g., in TP53), which I understand exists but maybe doesn't return patient IDs.

Once those are done, doing a join on patient IDs is relatively straightforward and can be simply implemented "above" the individual APIs, whether with something that looks like the discovery search API, or something that looks like GraphQL.   Implementing it in the flask server doesn't help us, except maybe slightly speeding up the treatment+diagnosis join; and even there, the performance difference of a linear join and something more sophisticated is going to be tiny for anything less than tens of thousands of patients, and even then will probably be dwarfed by the tabix searches for the variants.
